gtk4.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/gtk4.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/gtk4.c -o gtk4.lo 
src/G/GObject.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/G/GObject.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/G/GObject.c -o src/G/GObject.lo 
src/G/GApplication.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/G/GApplication.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/G/GApplication.c -o src/G/GApplication.lo 
src/Atk/AtkPlug.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Atk/AtkPlug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Atk/AtkPlug.c -o src/Atk/AtkPlug.lo 
src/Gtk/Gtk.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/Gtk.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/Gtk.c -o src/Gtk/Gtk.lo 
src/Gtk/GtkWidget.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/GtkWidget.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/GtkWidget.c -o src/Gtk/GtkWidget.lo 
src/Gtk/GtkApplication.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/GtkApplication.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/GtkApplication.c -o src/Gtk/GtkApplication.lo 
src/Gtk/GtkWindow.lo: /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/GtkWindow.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/backup/Bruno/BUILD_PHP_GTK/php-gtk4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/backup/Bruno/BUILD_PHP_GTK/php-gtk4/src/Gtk/GtkWindow.c -o src/Gtk/GtkWindow.lo 
$(phplibdir)/gtk4.la: ./gtk4.la
	$(LIBTOOL) --mode=install cp ./gtk4.la $(phplibdir)

./gtk4.la: $(shared_objects_gtk4) $(GTK4_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_gtk4) $(GTK4_SHARED_LIBADD)

